#!/bin/bash

echo "aws ec2 describe-instances --query 'Reservations[*].Instances[*].[Tags[?Key==\`Name\`].Value | [0], State.Name, PrivateIpAddress, LaunchTime ]' --output=table --region=eu-west-1 | grep -E --color=auto \"^|.*string-to-match.*\""| sudo su -s /bin/sh ec2-user -
